### ISSUE TITLE
更新rank表出错

### ISSUE THREAD

**Issue by Ayaneyume** [ColdThunder11/pcr-rank#12]
使用 设置rank更新源后bot无反应 ，更新rank表缓存后如图
麻烦冷雷大佬解答一下
![Uploading E0B55814F176A57B88E429CCBD3AA114.png…]()

**Comment by Ayaneyume** [comment]
![E0B55814F176A57B88E429CCBD3AA114](https://github.com/user-attachments/assets/1bd01ac5-2db8-4f6f-a3a8-6fec782baa01)

**Comment by ColdThunder11** [comment]
> ![E0B55814F176A57B88E429CCBD3AA114](https://private-user-images.githubusercontent.com/149157321/371919800-1bd01ac5-2db8-4f6f-a3a8-6fec782baa01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjI0NjEsIm5iZiI6MTcyNzY2MjE2MSwicGF0aCI6Ii8xNDkxNTczMjEvMzcxOTE5ODAwLTFiZDAxYWM1LTJkYjgtNGY2Zi1hM2E4LTZmZWM3ODJiYWEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwMjA5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGNkNGRmMGI3OTA4NjU2YTI3NmY1NTRkY2UyZWY1YmU4ZWI2ZjVkM2I1ODZiYzQ4ZjIxZjcyNWMzMzRlZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G4M-uuGgZQw1oGlod_uYd58CE5QU0QTvNFi68vdpX0A)

反代的服务器核爆了，晚上回去修

**Comment by Ayaneyume** [comment]
辛苦大佬啦

**Comment by ColdThunder11** [comment]
> 辛苦大佬啦

已恢复
