### ISSUE TITLE
请问一下，该插件下载的rank表图片是存放在哪里啊

### ISSUE THREAD

**Issue by imaginicleo** [ColdThunder11/pcr-rank#3]
我用该插件带的更新指令更新了一次rank表，现在b服的json文件已经改成了r12-4，但是在发送的时候有明显延迟且仅有文字无图片，后台也没有报错，所以想问问rank表图片是存放在哪里？

**Comment by ColdThunder11** [comment]
> 我用该插件带的更新指令更新了一次rank表，现在b服的json文件已经改成了r12-4，但是在发送的时候有明显延迟且仅有文字无图片，后台也没有报错，所以想问问rank表图片是存放在哪里？

默认是通过http的方式由go-cqhttp发送，今天晚上（不摸的话）会更新下允许本地发送和自动调整大小来解决图片发送失败的问题
