### ISSUE TITLE
更新缓存稳定报错

### ISSUE THREAD

**Issue by BJY666** [ColdThunder11/pcr-rank#9]
只要发出更新rank表缓存的命令就会稳定报错，而且json文件内容都会自动从下图左侧变为右侧的模样，报错的截图也在下图（很久没更新估计作者不会看，但还是先开个Issues占个坑位）
![QQ图片20230828231259](https://github.com/ColdThunder11/pcr-rank/assets/51154133/76e39b22-8698-470c-ac97-a6e7bffb70e9)
![QQ图片20230828231210](https://github.com/ColdThunder11/pcr-rank/assets/51154133/99b64cf9-4c7e-455d-8918-e84af518428f)

**Comment by BJY666** [comment]
PS：图一应该是从右侧变为左侧的样子

**Comment by ColdThunder11** [comment]
你的IP被clouflare标记为已知bot ip了，已经修改了防火墙规则再试试看

**Comment by BJY666** [comment]
感谢大佬，已经可以正常使用了。
以后要避免这种情况的话，魔法是不是要定期换节点才行？

**Comment by ColdThunder11** [comment]
我已经在防火墙规则里禁用了这个防护，以后应该不会被拦截
